ConfigurationData
| where ConfigDataType == "Software"
| where SoftwareType == "Patch"
| summarize LatestTime = max(TimeGenerated) by Computer
| join kind=inner (
    ConfigurationData
    | where ConfigDataType == "Software"
    | where SoftwareType == "Patch"
) on $left.Computer == $right.Computer and $left.LatestTime == $right.TimeGenerated
| project Computer, SoftwareName, CurrentVersion , Publisher
